name: covid19_contact_tracking
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  provider: ^6.0.2
  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.14
  intl_phone_number_input:
    git:
      url: 'https://github.com/kumsumit/intl_phone_number_input.git'
  flutter_spinkit: ^5.1.0
  enum_to_string: ^2.0.1
  pinput: ^2.2.7
  google_fonts: ^3.0.1
  pie_chart: ^5.3.0
  file_picker: ^4.5.1
  syncfusion_flutter_charts: ^20.1.57
  intl: ^0.17.0
  flutter_local_notifications: ^9.5.2
  geolocator: ^8.2.1
  beacons_plugin: ^2.0.8
  beacon_broadcast: ^0.3.1
  firebase_storage: ^10.2.18
  pdfx: ^2.0.1+2
  google_mlkit_barcode_scanning: ^0.3.0
  html: ^0.15.0
  web_scraper: ^0.1.4
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#4DCED7"
  image: "assets/covid19-logo-512x512.png"
  android: true
  ios: true


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Ebrima
      fonts:
        - asset: fonts/ebrima.ttf
        - asset: fonts/ebrimabd.ttf
          weight: 700
    - family: Century Gothic
      fonts:
        - asset: fonts/GOTHIC.ttf
        - asset: fonts/GOTHICB.ttf
          weight: 700
